### ISSUE TITLE
Issue with tutorials/nonparametric-trends/index.md

### ISSUE THREAD

**Issue by dumpling827** [google/earthengine-community#382] opened 2021-07-29 13:55 UTC
Issue Description: Why my layer "Kendall" is a full-white layer? Can anyone help me?

**Comment by jdbcode** [comment] 2021-08-03 17:11
Can you please send a link to the Code Editor script that demonstrates the issue (use the Get Link button).

**Comment by dumpling827** [comment] 2022-02-27 13:05
I'm very sorry to see this reply now, but I still haven't solved this problem. 
This is my code link, https://code.earthengine.google.com/2f43b5c769edcda9c4ad2a40e34552f4
Thank u so much!!!

**Comment by chelseadelgrande** [comment] 2022-05-31 21:27
I had this same issue. I had to change the sign code in row to float() instead of int(). Or at least that gave me something other than white.

var sign = function(i, j) { // i and j are images
  return ee.Image(j).neq(i) // Zero case
      .multiply(ee.Image(j).subtract(i).clamp(-1, 1)).**int();**
};

https://code.earthengine.google.com/6d2c663159d34c5e91423f9be01a717b

**Comment by dumpling827** [comment] 2022-05-31 21:27
谢谢，您发的邮件我已收到。

**Comment by dumpling827** [comment] 2022-06-01 11:30
> Thanks for your reply!!! But it didn't work... T~T
Maybe this problem related to my code above. I changed int() to float(), and the result layer just from full-white turned to full-red.

**Comment by geocodeworld** [comment] 2023-05-23 20:12
Hello everyone,
 I am facing an issue in exporting the Kendall output. The output is coming as a straight strip of red color. Can anyone inform me how to export the Kendall output for map preparation. 
Thanks

**Comment by gino-m** [comment] 2023-12-05 20:23
Hi all, sorry for the delayed response, we haven't been regularly monitoring this channel. Looking at the [published tutorial](https://developers.google.com/earth-engine/tutorials/community/nonparametric-trends) all results look correct. Are you seeing this issue when you modify the tutorial? If so, can you please post your question to one of our supported channels, providing a link to the modified notebook? You can find out more here:
https://developers.google.com/earth-engine/help

**Comment by n-clinton** [comment] 2023-12-06 14:35
I think this demo is working as intended.  From the first paragraph in the tutorial: "It is important to note that the methods presented here are suitable for assessing monotonic trends (i.e. data without seasonality) in discrete data (i.e. not floating point)."  Don't use float.  

Note that the input collection is unbounded (i.e. there's no filterDate()), so the results will actually change as the collection is updated.

Note that the datasets are added to the map without visualization parameters.  Specifically, the first layer added has a comment:
// Stretch this as necessary.

All the other layers should have that same comment.  In summary, you need to stretch the layers or otherwise fiddle with the visualization to get the display to look as it does in the tutorial.  Also, I recommend filtering to the specific date range of interest.

**Comment by jdbcode** [comment] 2024-01-09 20:31
Closing the issue - its sounds like most of the comments can be resolved by setting the visualization `min` and `max` parameters to match the data distribution. A quick way to set these is after displaying the data to the map, click on the layer settings in the layer manager and use the 98% or 2 standard deviation stretch options. Please reopen if these does not resolve your issues and redescribe them with code links and screen shots to indicate the problem.

**Closed by jdbcode** 2024-01-09 20:31 UTC
