### ISSUE TITLE
Issue with tutorials/nonparametric-trends/index.md

### ISSUE THREAD

**Issue by chelseadelgrande** [google/earthengine-community#525] opened 2022-05-31 21:30 UTC
Layer is all white when you use this code. Others seem to have this same issue (https://gis.stackexchange.com/questions/386323/about-mann-kendall-test-in-google-earth-engine). I believe this is related to using the int() function, which appears to be zeroing out all the data. When I changed that to float() I at least received something other than white on the map (though I'm not sure I can trust it).

https://code.earthengine.google.com/6d2c663159d34c5e91423f9be01a717b

var sign = function(i, j) { // i and j are images
  return ee.Image(j).neq(i) // Zero case
      .multiply(ee.Image(j).subtract(i).clamp(-1, 1)).int();
};

**Comment by gino-m** [comment] 2023-12-05 20:32
Duplicate of #382.

**Closed by gino-m** 2023-12-05 20:32 UTC
