### ISSUE TITLE
Issue with tutorials/modis-ndvi-time-series-animation/index.md

### ISSUE THREAD

**Issue by sherryoung** [google/earthengine-community#807] opened 2024-03-23 16:33 UTC
There is an issue when printing the GIF URL to the console. I used the same code and example as the one provided on the website.

"Setting the CRS, geodesic, or evenOdd flag on a computed Geometry is not supported.  Use Geometry.transform()."

**Comment by jdbcode** [comment] 2024-03-27 18:39
I can't reproduce the issue when running the unmodified demo.

Are you changing the `region` variable?

Could you could share the Code Editor script that produces the error?

**Comment by jdbcode** [comment] 2024-04-21 16:55
Closing for now. Reopen if this is still an issue for you and please include a reproducible script.

**Closed by jdbcode** 2024-04-21 16:55 UTC
