### ISSUE TITLE
Issue with tutorials/nonparametric-trends/index.md

### ISSUE THREAD

**Issue by 44jean** [google/earthengine-community#646] opened 2023-03-07 14:59 UTC
Issue Description

hey there,

First, thanks a lot for developing this amazing algorithm page(nonparametric-trends) and giving a very nice tutorial, it really helps !!!! 

But i got stuck. Here is my problem: My research object is an index from 0 to 1 and in order to use this algorithm( not float type), I multiply 100 to each pixel. And the slope result is perfect according to different papers, the figure is correct, and my follow-up research is so successful that I almost forget i multiplied 100 to each pixel.  
CAN this result represent the actual trend even though I multiplied 100 because i think the Intercept eliminate it?

However, I multiplied 10000 to each pixel trying to verify my thought, the result is different.....

I want to ask is there any solution to this situation? Can i change the code to make it suitable for float data?

here is my result👇，
![20230307224057](https://user-images.githubusercontent.com/89766745/223455099-776c9c5e-2210-4504-8b39-9f8e96f63e42.png)
and my GEE link👇
https://code.earthengine.google.com/3c69bf9d39b678050f898f7ad94f6c88

**Comment by 44jean** [comment] 2023-03-11 14:26
hey, I think I solved this problem. But i am not sure.

It turns out that float time series data can execute the code in the Page: nonparametric-trends and the figure is similar to results of  ee.Reducer.linearFit() and ee.Reducer.sensSlope().

**Comment by jdbcode** [comment] 2023-12-28 00:42
Apologies that it has taken so long to respond - the issues have been neglected for a while. We're go through them now. Your link is an empty script, so I can't reproduce to investigate. I'm going to close this for now - reopen and add a reproducible script if you'd still like us to look at it.

**Closed by jdbcode** 2023-12-28 00:42 UTC
